// ESHTTP canonical ExtendScript (JSX) emission — shared ESTC pipeline.
//
// The JSX artifact is emitted by the shared toolchain:
//   esbuild ES5 IIFE -> bundle-local esbuild-helper localization ->
//   UglifyJS ExtendScript-safe re-emission -> parser-output repair ->
//   strict ES3/static gate.
//
// No compatibility shims and no persistent built-in patches: the entry is
// side-effect only (src/jsx-entry.ts) so no descriptor-dependent esbuild
// export helper is generated at all, and src/index.ts guards its own
// Object.defineProperty uses with the toolchain's verified feature-guard form.
//
// The embedded ESON/ESB64 self-extracting payload strings are generated
// sibling artifacts supplied as a prelude (byte-exact data, not code) so the
// shipped artifact is ONE checked ESTC emission. eshttp-build.mjs verifies
// payload byte-fidelity after the build.
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const ESON_ACCEL = join(ROOT, '..', 'eson', 'dist', 'ESON.accel.min.jsx');
const ESB64_ACCEL = join(ROOT, '..', 'esb64', 'dist', 'ESB64.accel.min.jsx');

function payloadDecls() {
  const missing = [];
  if (!existsSync(ESON_ACCEL)) {
    missing.push(ESON_ACCEL + '  (run `node eson-build.mjs --accel` in ../eson)');
  }
  if (!existsSync(ESB64_ACCEL)) {
    missing.push(ESB64_ACCEL + '  (run `node esb64-build.mjs --accel` in ../esb64)');
  }
  if (missing.length) {
    throw new Error('[eshttp estc config] embedded accel payloads missing:\n  ' + missing.join('\n  '));
  }
  const eson = readFileSync(ESON_ACCEL, 'utf8');
  const esb64 = readFileSync(ESB64_ACCEL, 'utf8');
  return [
    '// GENERATED by extendscript.estc.config.mjs — embedded ESPACK-accelerated sibling bundles.',
    '//   ../eson/dist/ESON.accel.min.jsx',
    '//   ../esb64/dist/ESB64.accel.min.jsx',
    '// Byte-exact generated payload data; verified after build by eshttp-build.mjs.',
    'var ESON_ACCEL_BUNDLE = ' + JSON.stringify(eson) + ';',
    'var ESB64_ACCEL_BUNDLE = ' + JSON.stringify(esb64) + ';'
  ].join('\n');
}

export default {
  host: 'illustrator',
  hostTypes: 'Illustrator/2022',
  additionalTypes: ['./src/globals.d.ts', './types/estc-es3-vocabulary.d.ts'],
  entry: 'src/jsx-entry.ts',
  outfile: 'dist/eshttp.jsx',
  target: 'illustrator',
  requireTarget: false,
  sourceLint: true,
  typecheck: true,
  normalize: true,
  compatibilityTransforms: ['esbuild'],
  compatibilityShims: [],
  allowedMissingBuiltins: [],
  allowedGlobalPatches: [],
  prelude: [{ code: payloadDecls() }],
  footer: [{ file: 'tooling/estc-unwrap-footer.js' }],
  allowJson: false,
  allowIncludes: false,
  live: false,
  liveLaunch: false
};
